### ISSUE TITLE
Feedback v/ Fabienne

### ISSUE THREAD

**Issue by Fabienne02** [Kuckelkorn/foodchecker#1]
HTML: duidelijk en goed, niet nodig maar meta kan groter ig? 
    meta name="description" content="" 
    meta name="keywords" content="" 
    meta name="author" content="" 

CSS: Kan een beautifyer op verder duidelijk. 

JS: Behalve dat ik meerdere JS files onhandig vind ziet het er erg goed uit! :)

**Comment by Kuckelkorn** [comment]
CSS file is aangepast en heeft nu een gestructureerdere volgorde
